### ISSUE TITLE
Auto restart if application stops

### ISSUE THREAD

**Issue by codemasteryofficial** [AFreeChameleon/multask#31]
Auto restart if application stops with exponential delay, would be a great feature to this application

**Comment by AFreeChameleon** [comment]
Thanks for giving this project a look! I've got auto restarting planned for this upcoming release so expect it to be added then :)

**Comment by dhruba-ai** [comment]
I tried this in mac with release build, but I think this is not working, am I missing something
STEPS to reproduce
1. create a test.js file
setInterval(()=>{
    if(Math.random() > 0.8){
        throw new Error('error')
    }
    console.log(1)
}, 2000)

2. ./mlt create "node test.js"

**Comment by codemasteryofficial** [comment]
I tried this in mac with release build, but I think this is not working, am I missing something?

STEPS to reproduce

1) create a test.js file with bellow code
setInterval(()=>{
  if(Math.random() > 0.8){
     throw new Error('error')
  }
  console.log(1)
}, 2000)

2) ./mlt create "node test.js"
